"""empty message

Revision ID: 15fbd4e8ee4f
Revises: 
Create Date: 2014-12-15 23:03:02.837299

"""

# revision identifiers, used by Alembic.
revision = '15fbd4e8ee4f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'anchor_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_projecttags_tag_id'), 'projecttags', ['tag_id'], unique=False)
    op.drop_index('fki_project_tags_tag_id_fkey', table_name='projecttags')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fki_project_tags_tag_id_fkey', 'projecttags', ['tag_id'], unique=False)
    op.drop_index(op.f('ix_projecttags_tag_id'), table_name='projecttags')
    op.alter_column('project', 'anchor_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
